FROM openjdk:11

WORKDIR /app

#COPY target/scala-2.12/producer-app-assembly-1.0.0-SNAPSHOT.jar /app/producer.jar
#COPY dataset_cac40/CAC40_stocks_2010_2021.csv /data/dataset_cac40/CAC40_stocks_2010_2021.csv

CMD ["java", "-jar", "producer-app-assembly-1.0.0-SNAPSHOT.jar"]